// Package codegen compiles a Plan into standalone Go source — the scale path.
//
// It does NOT reimplement any generator: emitted code calls the same exposed
// seams the interpreter uses (data.MustBuild, schema.RowSource/RefIndex/
// UniqueValue) with the same source-addressing order, so its output is identical
// to `--seed` by construction. What it removes is the per-row overhead: the
// map[string]any record, the reflection/fmt formatting, and the registry lookup
// per row — replaced by typed structs and strconv writes.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"sort"
	"strconv"
	"strings"

	"github.com/scalecode-solutions/mvfaker/data"
	"github.com/scalecode-solutions/mvfaker/schema"
)

// Emit writes a generated Go package for the plan to w.
func Emit(p *schema.Plan, pkg string, w io.Writer) error {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by mvfaker; DO NOT EDIT.\n\npackage %s\n\n", pkg)
	b.WriteString(`import (
	"bufio"
	"io"
	"strconv"
	"strings"

	"github.com/scalecode-solutions/mvfaker/data"
	"github.com/scalecode-solutions/mvfaker/schema"
)

func _copyEsc(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\t", "\\t")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	return s
}

`)

	for _, name := range p.Order {
		e := p.Entities[name]
		if e.IDType == "none" || len(e.DistinctPair) > 0 {
			return fmt.Errorf("codegen does not yet support id_type=none / distinct_pair (entity %q); use the interpreter (--seed)", name)
		}
		for _, f := range e.Fields {
			if f.Ref != "" && f.Unique {
				return fmt.Errorf("codegen does not yet support unique refs (%s.%s); use the interpreter (--seed)", name, f.Name)
			}
			if f.Transform != "" || f.MaxLen > 0 || f.NullProb > 0 || f.When != "" {
				return fmt.Errorf("codegen does not yet support field modifiers "+
					"(transform/maxlen/null_prob/when); %s.%s uses one — use the interpreter (--seed)", name, f.Name)
			}
		}
		emitStruct(&b, p, e)
		emitBuilders(&b, e)
		emitGen(&b, p, e)
		emitSeed(&b, p, e)
	}
	emitSeedAll(&b, p)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("codegen produced invalid Go: %w\n%s", err, b.String())
	}
	_, err = w.Write(src)
	return err
}

func emitStruct(b *bytes.Buffer, p *schema.Plan, e *schema.Entity) {
	fmt.Fprintf(b, "type %s struct {\n\tID %s\n", exportName(e.Name), idGoType(e))
	for _, f := range e.Fields {
		fmt.Fprintf(b, "\t%s %s\n", exportName(f.Name), fieldGoType(p, f))
	}
	b.WriteString("}\n\n")
}

func emitBuilders(b *bytes.Buffer, e *schema.Entity) {
	any := false
	for _, f := range e.Fields {
		if f.Ref != "" {
			continue
		}
		if !any {
			b.WriteString("var (\n")
			any = true
		}
		fmt.Fprintf(b, "\t%s = data.MustBuild(%q, %s)\n", varName(e.Name, f.Name), f.Gen, paramsLiteral(f.Params))
	}
	if any {
		b.WriteString(")\n\n")
	}
}

func emitGen(b *bytes.Buffer, p *schema.Plan, e *schema.Entity) {
	fmt.Fprintf(b, "func Gen%s(seed uint64, id, count int) %s {\n", exportName(e.Name), exportName(e.Name))
	fmt.Fprintf(b, "\tsrc := schema.RowSource(seed, %q, id)\n\tvar r %s\n", e.Name, exportName(e.Name))
	if e.IDType == "uuid" {
		fmt.Fprintf(b, "\tr.ID = schema.UUIDFor(seed, %q, id)\n", e.Name)
	} else {
		b.WriteString("\tr.ID = id\n")
	}
	refIdxVar := map[string]string{} // ref field -> local index var name
	refTgt := map[string]string{}    // ref field -> target entity
	for _, f := range e.Fields {
		if f.Ref != "" {
			target := refTargetName(f.Ref)
			iv := "ix_" + ident(f.Name)
			fmt.Fprintf(b, "\t%s := schema.RefIndex(seed, %q, id, %q, %d)\n", iv, e.Name, f.Ref, p.Counts[target])
			refIdxVar[f.Name], refTgt[f.Name] = iv, target
			if te := p.Entities[target]; te != nil && te.IDType == "uuid" {
				fmt.Fprintf(b, "\tr.%s = schema.UUIDFor(seed, %q, %s)\n", exportName(f.Name), target, iv)
			} else {
				fmt.Fprintf(b, "\tr.%s = %s\n", exportName(f.Name), iv)
			}
			continue
		}
		dep := "nil"
		if f.From != "" {
			if i := strings.IndexByte(f.From, '.'); i >= 0 { // cross-entity projection
				local, tf := f.From[:i], f.From[i+1:]
				if te, iv := refTgt[local], refIdxVar[local]; te != "" && iv != "" {
					dep = fmt.Sprintf("any(Gen%s(seed, %s, %d).%s)", exportName(te), iv, p.Counts[te], exportName(tf))
				}
			} else {
				dep = "any(r." + exportName(f.From) + ")"
			}
		}
		b.WriteString("\t{\n")
		fmt.Fprintf(b, "\t\tv := %s(%s).Generate(src.Split())\n", varName(e.Name, f.Name), dep)
		if f.Unique {
			fmt.Fprintf(b, "\t\tv = schema.UniqueValue(v, id, count, seed, %q, %q)\n", e.Name, f.Name)
		}
		fmt.Fprintf(b, "\t\tr.%s = v.(%s)\n\t}\n", exportName(f.Name), fieldGoType(p, f))
	}
	b.WriteString("\treturn r\n}\n\n")
}

func emitSeed(b *bytes.Buffer, p *schema.Plan, e *schema.Entity) {
	cols := []string{"id"}
	for _, f := range e.Fields {
		cols = append(cols, f.Name)
	}
	fmt.Fprintf(b, "func Seed%ss(w io.Writer, seed uint64, n int) error {\n", exportName(e.Name))
	b.WriteString("\tbw := bufio.NewWriter(w)\n\tdefer bw.Flush()\n")
	fmt.Fprintf(b, "\tif _, err := io.WriteString(bw, %q); err != nil {\n\t\treturn err\n\t}\n",
		fmt.Sprintf("COPY %s (%s) FROM stdin;\n", e.Name, strings.Join(cols, ", ")))
	b.WriteString("\tfor i := 0; i < n; i++ {\n")
	fmt.Fprintf(b, "\t\tr := Gen%s(seed, i, n)\n", exportName(e.Name))
	emitFieldWrite(b, "r.ID", idGoType(e))
	for _, f := range e.Fields {
		b.WriteString("\t\tbw.WriteByte('\\t')\n")
		emitFieldWrite(b, "r."+exportName(f.Name), fieldGoType(p, f))
	}
	b.WriteString("\t\tbw.WriteByte('\\n')\n\t}\n")
	b.WriteString("\tif _, err := io.WriteString(bw, \"\\\\.\\n\"); err != nil {\n\t\treturn err\n\t}\n\treturn bw.Flush()\n}\n\n")
}

func emitFieldWrite(b *bytes.Buffer, expr, gt string) {
	switch gt {
	case "int":
		fmt.Fprintf(b, "\t\tbw.WriteString(strconv.Itoa(%s))\n", expr)
	case "bool":
		fmt.Fprintf(b, "\t\tif %s {\n\t\t\tbw.WriteByte('t')\n\t\t} else {\n\t\t\tbw.WriteByte('f')\n\t\t}\n", expr)
	default:
		fmt.Fprintf(b, "\t\tbw.WriteString(_copyEsc(%s))\n", expr)
	}
}

func emitSeedAll(b *bytes.Buffer, p *schema.Plan) {
	b.WriteString("func SeedAll(w io.Writer, seed uint64) error {\n")
	for _, name := range p.Order {
		fmt.Fprintf(b, "\tif err := Seed%ss(w, seed, %d); err != nil {\n\t\treturn err\n\t}\n",
			exportName(name), p.Counts[name])
	}
	b.WriteString("\treturn nil\n}\n")
}

// --- helpers ---------------------------------------------------------------

func refTargetName(ref string) string {
	if k := strings.IndexByte(ref, '.'); k >= 0 {
		return ref[:k]
	}
	return ref
}

// idGoType is the Go type of an entity's primary key: string for uuid, else int.
func idGoType(e *schema.Entity) string {
	if e.IDType == "uuid" {
		return "string"
	}
	return "int"
}

// fieldGoType is the Go type of a field. A ref takes its *target's* id type.
func fieldGoType(p *schema.Plan, f *schema.Field) string {
	if f.Ref != "" {
		if te := p.Entities[refTargetName(f.Ref)]; te != nil {
			return idGoType(te)
		}
		return "int"
	}
	switch f.Gen {
	case "number":
		return "int"
	case "bool":
		return "bool"
	default:
		return "string"
	}
}

func exportName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		switch {
		case p == "":
		case p == "id":
			parts[i] = "ID"
		default:
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func varName(entity, field string) string {
	return "_mk_" + ident(entity) + "_" + ident(field)
}

func ident(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

func paramsLiteral(p data.Params) string {
	if len(p) == 0 {
		return "nil"
	}
	keys := make([]string, 0, len(p))
	for k := range p {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("data.Params{")
	for i, k := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q: %s", k, valueLiteral(p[k]))
	}
	b.WriteString("}")
	return b.String()
}

func valueLiteral(v any) string {
	switch x := v.(type) {
	case int:
		return strconv.Itoa(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case float64:
		return strconv.FormatFloat(x, 'g', -1, 64)
	case bool:
		return strconv.FormatBool(x)
	case string:
		return strconv.Quote(x)
	default:
		return fmt.Sprintf("%#v", x)
	}
}
